### ISSUE TITLE
Unable to stop mid climbing.

### ISSUE THREAD

**Issue by jiwachow** [artemisSystem/better-climbing#2]
Before installing the mod, I could stop on a ladder and start making tunnel at the height I stopped.

After installing the mod, I can't or don't know how to stop on a ladder, and unless I destroy the ladder at the point I want to make new tunnel I can't stop.

Please implement a button, or make it more clear on how to stop mid climbing.

**Comment by artemisSystem** [comment]
Are you not able to hold shift/sneak to stop/hold on to a ladder? Which modloader are you using, and are you playing with any other mods?

**Comment by jiwachow** [comment]
Yes I can't.
Yes, multiple mods. 
Quit modloader.

Latest log with mods specified:
https://paste.ee/p/pBlZo

**Comment by artemisSystem** [comment]
That is a lot of mods, so it's gonna be hard for me to download them all and check this out myself. So we'll try one thing first:
Can you try adding `-Dmixin.debug.export=true` to your launch arguments, and then finding the file `.minecraft/.mixin.out/class/net/minecraft/class_1309.class`, zipping it up, and sending it here? When you turn it into a .zip you can just drag and drop it right into the github text window.
If you need some help with this, you can join the [violet moon discord](https://discord.gg/vm), and ping me (artemisSystem#3141) in the #help channel

**Comment by jiwachow** [comment]
[class_1309.zip](https://github.com/artemisSystem/better-climbing/files/10472062/class_1309.zip)

Found it!

**Comment by jiwachow** [comment]
I tried joining but it says invite is invalid

**Comment by artemisSystem** [comment]
Thanks! Perfect.

The other mods that touch this code seems to be:
- Peculiar Pieces
- Platforms
- Pekhui

I already know Peculiar Pieces does its mixin badly, which conflicts with Better Climbing, making the fast downwards climbing not work at all, if i recall correctly. Maybe try without peculiar pieces first, and then also try all the other combinations of these mods to see which are causing the issue?

**Comment by jiwachow** [comment]
It was Peculiar Pieces. Thank you for your help.
