### ISSUE TITLE
1.20+ version not labeled as 1.20.2 on websites?

### ISSUE THREAD

**Issue by RandomGgames** [artemisSystem/better-climbing#3]
Hey! Looks like this mod is working on 1.20.2, however everywhere I see it posted, it says 1.20.1 only. Could you set it as 1.20.2 compatible as well?
https://modrinth.com/mod/better-climbing/versions
https://www.curseforge.com/minecraft/mc-mods/better-climbing/files?page=1&pageSize=20

**Comment by artemisSystem** [comment]
Oh yeah, was gonna do that but forgot. thanks for checking that it works!
