### ISSUE TITLE
Update to 1.21

### ISSUE THREAD

**Issue by RandomGgames** [artemisSystem/better-climbing#4]
Hey! Out of curiosity will this be updated to 1.21? Thanks!

**Comment by artemisSystem** [comment]
The fabric version works fine on 1.21, so i've updated the data on modrinth and curseforge to be correct on that. The forge version seems to only work up until 1.20.4, so i'll try to update to neoforged 1.21 in the near future. Thanks!

**Comment by artemisSystem** [comment]
https://modrinth.com/mod/better-climbing/version/4-neoforge
https://www.curseforge.com/minecraft/mc-mods/better-climbing/files/5514197

**Comment by RandomGgames** [comment]
Thanks! Love the mod :)
